### ISSUE TITLE
Table content not selectable

### ISSUE THREAD

**Issue by Dazzel** [DataTables/Responsive#68]
When using ```responsive.details.column``` it is impossible to select data inside the table.

**Comment by DataTables** [comment]
Please link to a test case should the issue.

**Comment by Dazzel** [comment]
See the examples where the column type is used: https://datatables.net/extensions/responsive/examples/child-rows/column-control.html

**Comment by DataTables** [comment]
Thanks - I understand now. This was resolved by 1305a7f31120a75444255023ba573d3b83aefa38. It will be in the next release and is already in the nightly version.

**Comment by vafada** [comment]
Is e.preventDefault() the best fix here? why not add a CSS property ```outline: none``` ?

**Comment by DataTables** [comment]
`outline:none` isn't appropriate for the library since it causes problems with keyboard accessibility.

As you seeing a problem with using `preventDefault`?

**Comment by vafada** [comment]
the fix looks good. I can highlight the child row text now. though I still can't highlight the text in the first column. Probably intended since the first column is used to toggle?

**Comment by DataTables** [comment]
Hmm - its not aIts not intended, but it might be a consequence of it. Reopening this issue so I remember to look into in detail and see if that can be resolved.
